# Generated by Django 5.2.6 on 2026-06-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('partyname', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Party Name')),
                ('add1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('add2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('gst', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile No.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('opdr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Opening Debit (Dr)')),
                ('opcr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Opening Credit (Cr)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['partyname'],
            },
        ),
    ]
