# Generated by Django 5.2.6 on 2026-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemname', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Item Name')),
                ('mode_of_change', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=10, verbose_name='Mode of Change')),
                ('storage_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Storage Charge')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['itemname'],
            },
        ),
    ]
