# Generated by Django 5.2.6 on 2026-06-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMaster',
            fields=[
                ('incomingno', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Incoming No')),
                ('incoming_date', models.DateField(verbose_name='Incoming Date')),
                ('lotno', models.CharField(max_length=100, verbose_name='Lot No')),
                ('store_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Store Code')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomings', to='master.party', verbose_name='Party')),
            ],
            options={
                'verbose_name': 'Incoming Master',
                'verbose_name_plural': 'Incoming Masters',
                'ordering': ['-incoming_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20, verbose_name='Mode')),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Qty')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rate')),
                ('store_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Store Charge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_details', to='master.item', verbose_name='Item')),
                ('incoming_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='master.incomingmaster')),
            ],
            options={
                'verbose_name': 'Incoming Detail',
                'verbose_name_plural': 'Incoming Details',
            },
        ),
    ]
