# Generated by Django 5.2.6 on 2026-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_incomingmaster_incomingdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='Start Date')),
                ('enddate', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Final Year',
                'verbose_name_plural': 'Final Years',
                'ordering': ['-startdate'],
            },
        ),
    ]
