# Generated by Django 5.2.6 on 2026-06-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_finalyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPMaster',
            fields=[
                ('gpno', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='GP No')),
                ('gpdate', models.DateField(verbose_name='GP Date')),
                ('gptime', models.TimeField(verbose_name='GP Time')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Qty')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Storage Location')),
                ('recon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rec No')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses', to='master.party', verbose_name='Client Name')),
            ],
            options={
                'verbose_name': 'GP Master',
                'verbose_name_plural': 'GP Masters',
                'ordering': ['-gpdate', '-gptime'],
            },
        ),
        migrations.CreateModel(
            name='GPDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Qty')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_details', to='master.item', verbose_name='Item')),
                ('gp_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='master.gpmaster', verbose_name='GP Master')),
            ],
            options={
                'verbose_name': 'GP Detail',
                'verbose_name_plural': 'GP Details',
            },
        ),
    ]
