# Generated by Django 5.2.6 on 2026-06-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_gpmaster_gpdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentno', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Payment No')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer'), ('Online', 'Online')], default='Cash', max_length=50, verbose_name='Mode of Payment')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('incoming_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='master.incomingmaster', verbose_name='Incoming No')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='master.party', verbose_name='Party')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date', 'paymentno'],
            },
        ),
    ]
