# Generated by Django 5.2.6 on 2026-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Bank'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True, verbose_name='Cheque Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheque No'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', max_length=50, verbose_name='Mode of Payment'),
        ),
    ]
