# Generated by assistant to rename Party table to ClientDetails
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_payment_bank_name_payment_cheque_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Party',
            new_name='ClientDetails',
        ),
        migrations.RunSQL(
            sql="ALTER TABLE master_party RENAME TO master_clientdetails;",
            reverse_sql="ALTER TABLE master_clientdetails RENAME TO master_party;",
        ),
        migrations.AlterModelTable(
            name='ClientDetails',
            table='master_clientdetails',
        ),
    ]
