# Generated by Django 5.2.6 on 2026-06-25 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_rename_payment_party_to_client_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdetails',
            options={'ordering': ['client_name'], 'verbose_name': 'Client Details', 'verbose_name_plural': 'Client Details'},
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_name',
            field=models.CharField(db_column='partyname', max_length=200, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='client_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='crdays',
            field=models.IntegerField(default=0, verbose_name='CrDays'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='crlimit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='CrLimit'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='opcr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='OpCr'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='opdr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='OpDr'),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='gpmaster',
            name='client_details',
            field=models.ForeignKey(db_column='client_name_id', on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses', to='master.clientdetails', verbose_name='Client Details'),
        ),
        migrations.AlterField(
            model_name='incomingmaster',
            name='client_details',
            field=models.ForeignKey(db_column='party_id', on_delete=django.db.models.deletion.CASCADE, related_name='incomings', to='master.clientdetails', verbose_name='Client Details'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_details',
            field=models.ForeignKey(db_column='party_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='master.clientdetails', verbose_name='Client Details'),
        ),
        migrations.CreateModel(
            name='HamaliEntry',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Entry No')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Entry Date')),
                ('hamali_type', models.CharField(max_length=100, verbose_name='Hamali Type')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rate')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Qty')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('lot_no', models.CharField(blank=True, max_length=100, verbose_name='Lot No')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hamali_entries', to='master.item', verbose_name='Item')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hamali_entries', to='master.clientdetails', verbose_name='Party')),
            ],
            options={
                'verbose_name': 'Hamali Entry',
                'verbose_name_plural': 'Hamali Entries',
                'ordering': ['-entry_date', '-entry_no'],
            },
        ),
    ]
